### ISSUE TITLE
How to open pages for user interaction?

### ISSUE THREAD

**Issue by StepIg** [dalenguyen/selenium-javascript#1]
Hi
Is it possible to open google.com and let the user interact with the page?
I also need my testers can launch the test from their homes.
How can i do this, please?
thanks in advance

**Comment by dalenguyen** [comment]
Hi @StepIg, you can run and interact with most of the sites by using selenium. The test can be run on any computers as long as they have a selenium server, chromedriver. If you need to open Google, you have to replace the URL in the example and rewrite the test cases based on your needs. 

For better report and test management, you can check out this: https://github.com/dalenguyen/WebdriverIO-TypeScript-Boilerplate
